package com.example.seijakulist.ui.theme

import androidx.compose.ui.graphics.Color

// Colores principales de la paleta


// Colores del tema Oscuro
val DarkPrimary = Color(0xFF4f6070)
val DarkOnPrimary = Color(0xFFb7c9da)
val DarkBackground = Color(0xFF212121)

val DarkSecondary = Color(0xFFc1c7cf)
val DarkOnSecondary = Color(0xFF2b3137)
val DarkTertiary = Color(0xFFd5c0d8)
val DarkOnTertiary = Color(0xFF392b3e)
val DarkError = Color(0xFFffb4ab)
val DarkOnError = Color(0xFF690005)
val DarkPrimaryContainer = Color(0xFF454758)
val DarkOnPrimaryContainer = Color(0xFFbccee0)
val DarkSecondaryContainer = Color(0xFF41474e)
val DarkOnSecondaryContainer = Color(0xFFb0b6bd)
val DarkTertiaryContainer = Color(0xFF615165)
val DarkOnTertiaryContainer = Color(0xFFe9dde6)
val DarkErrorContainer = Color(0xFF93000a)
val DarkOnErrorContainer = Color(0xFFffdad6)
val DarkSurfaceDim = Color(0xFF131314)
val DarkSurface = Color(0xFF131314)
val DarkSurfaceBright = Color(0xFF39393a)
val DarkSurfaceContainerLowest = Color(0xFF0d0e0f)
val DarkSurfaceContainerLow = Color(0xFF1b1c1d)
val DarkSurfaceContainer = Color(0xFF1f2021)
val DarkSurfaceContainerHigh = Color(0xFF292a2b)
val DarkSurfaceContainerHighest = Color(0xFF343536)
val DarkOnSurface = Color(0xFFe4e2e3)
val DarkOnSurfaceVariant = Color(0xFFc3c7cc)
val DarkOutline = Color(0xFF8d9196)
val DarkOutlineVariant = Color(0xFF43474b)
val DarkInverseSurface = Color(0xFFe4e2e3)
val DarkInverseOnSurface = Color(0xFF303031)
val DarkInversePrimary = Color(0xFF638EB6)
val DarkShadow = Color(0xFF000000)
val DarkScrim = Color(0xFF000000)



// Colores del tema Claro
val LightPrimary = Color(0xFF30414f)
val LightOnPrimary = Color(0xFFffffff)
val LightBackground = Color(0xFFffffff)
val LightSecondary = Color(0xFF595f66)
val LightOnSecondary = Color(0xFFffffff)
val LightTertiary = Color(0xFF493a4d)
val LightOnTertiary = Color(0xFFffffff)
val LightError = Color(0xFFba1b1b)
val LightOnError = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFF475867)
val LightOnPrimaryContainer = Color(0xFFbccee0)
val LightSecondaryContainer = Color(0xFFdde3eb)
val LightOnSecondaryContainer = Color(0xFF5f656c)
val LightTertiaryContainer = Color(0xFF615165)
val LightOnTertiaryContainer = Color(0xFFdbc5dd)
val LightErrorContainer = Color(0xFFffdad6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurfaceDim = Color(0xFFdbd9db)
val LightSurface = Color(0xFFfbf9fa)
val LightSurfaceBright = Color(0xFFfbf9fa)
val LightSurfaceContainerLowest = Color(0xFFffffff)
val LightSurfaceContainerLow = Color(0xFFf5f3f4)
val LightSurfaceContainer = Color(0xFFefedee)
val LightSurfaceContainerHigh = Color(0xFFDADCDE)
val LightSurfaceContainerHighest = Color(0xFFe9e8e9)
val LightOnSurface = Color(0xFF1b1c1d)
val LightOnSurfaceVariant = Color(0xFF43474b)
val LightOutline = Color(0xFF74777c)
val LightOutlineVariant = Color(0xFFe4e2e3)
val LightInverseSurface = Color(0xFF303031)
val LightInverseOnSurface = Color(0xFFf2f0f1)
val LightInversePrimary = Color(0xFF638EB6)
val LightShadow = Color(0xFF000000)
val LightScrim = Color(0xFF000000)